### ISSUE TITLE
[0.1.4] Unknown error location in fix_resolv_conf

### ISSUE THREAD

**Issue by nickgerace** [containers/krunvm#4]
# Description

I tried to use the [rancher/k3d](https://hub.docker.com/r/rancher/k3d) image from DockerHub and create a VM with it. I assumed that this would fail, but I would love to piece together why.

```bash
[root at fedora in ~/krunvm] (101) (main)
% RUST_BACKTRACE=1 krunvm create rancher/k3d --name k3d-test
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/create.rs:134:36
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: krunvm::create::create
   4: krunvm::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I believe in the `.unwrap()` call on line 134, an error was returned from the below function.

https://github.com/containers/krunvm/blob/367898a940585ce592e1e5e90f0690b568a78b62/src/create.rs#L11-L18

In order to figure out what happened, I would love to be able to see the exact error encountered from the called function. 
From my own edits, I can see that it occurred at this line...

```rust
let mut file = File::create(resolvconf)?; 
```

However, I did not find the above line without running `cargo run` with some edits and logging added.
Perhaps, there could be recommended suggestions based on what kind of error occurred and where :)

# Environment

Command | Output
--- | ---
`krunvm -V` | `krunvm 0.1.4`
`uname -r` | `5.10.15-200.fc33.x86_64`
`cat /etc/os-release \| grep "^PRETTY_NAME"` | `PRETTY_NAME="Fedora 33 (Server Edition)"`

# Other

Thank you! This is a wonderful project, by the way.

**Comment by slp** [comment]
Thanks for reporting this and for already proposing a fix in #5, it's really appreaciated.

BTW, this is the third time I'm aware of someone attemting to use `krunvm` to run `k3s` (or similar), so I'm starting to think this can be a popular use case. Do you think that can be the case?

I'm asking because it's very likely that the kernel bundled in [libkrunfw](https://github.com/containers/libkrunfw) is missing some features (specially in the networking field) needed to run it. But, if this is something people find useful, I think we might be able to justify adding a bit more of weight to the kernel.

**Comment by nickgerace** [comment]
Thank you for the comment and context @slp! Yes I think there would be a huge use case. I'm wondering if we can get the benefits of process isolation with ability to stand up inner-cluster networking. k3s runs in a single process, and (mostly) requires "only" systemd and the kernel. I think even having k3s work without access to public internet is still starting to head in a useful direction. I'd be more than happy to collaborate on this.

**Comment by slp** [comment]
Sounds interesting! Is the intention to run multiple nodes on the same Host on different krunvm instances? Would that node require a different IP? That's a use case that krunvm doesn't support out-of-the-box, but might still be possible by manually configuring a veth pair and running krunvm in the network namespace of one of them.

**Comment by nickgerace** [comment]
Actually the idea would be to get a single node k3s instance running, which would only require one krunvm instance. Of course, multi-node is a good goal, but not required upfront. I wonder what would need to be added to libkrunfw for that to happen.

**Comment by slp** [comment]
I found some time to play with k3s on krunvm, and I got pretty far, to the point I was able to get the node in `Ready` status, and deploy the [PHP Guestbook example](https://kubernetes.io/docs/tutorials/stateless-application/guestbook/), with some quirks.

So far, I identified the need to enable the following features in the kernel:

```
CONFIG_CPU_IDLE_GOV_HALTPOLL=y
CONFIG_NET_IP_TUNNEL=y
CONFIG_NET_UDP_TUNNEL=y
CONFIG_NETFILTER=y
CONFIG_NETFILTER_ADVANCED=y
CONFIG_BRIDGE_NETFILTER=y
CONFIG_NETFILTER_FAMILY_BRIDGE=y
CONFIG_NF_CONNTRACK=y
CONFIG_NF_CONNTRACK_MARK=y
CONFIG_NF_NAT=y
CONFIG_NF_NAT_MASQUERADE=y
CONFIG_NETFILTER_XTABLES=y
CONFIG_NETFILTER_XT_MARK=y
CONFIG_NETFILTER_XT_CONNMARK=y
CONFIG_NETFILTER_XT_TARGET_CONNMARK=y
CONFIG_NETFILTER_XT_NAT=y
CONFIG_NETFILTER_XT_TARGET_MASQUERADE=y
CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y
CONFIG_NETFILTER_XT_MATCH_COMMENT=y
CONFIG_NETFILTER_XT_MATCH_CONNMARK=y
CONFIG_NETFILTER_XT_MATCH_CONNTRACK=y
CONFIG_NETFILTER_XT_MATCH_MARK=y
CONFIG_NETFILTER_XT_MATCH_MULTIPORT=y
CONFIG_NETFILTER_XT_MATCH_STATISTIC=y
CONFIG_NETFILTER_XT_MATCH_U32=y
CONFIG_NF_DEFRAG_IPV4=y
CONFIG_NF_REJECT_IPV4=y
CONFIG_IP_NF_IPTABLES=y
CONFIG_IP_NF_FILTER=y
CONFIG_IP_NF_TARGET_REJECT=y
CONFIG_IP_NF_NAT=y
CONFIG_IP_NF_TARGET_MASQUERADE=y
CONFIG_IP_NF_MANGLE=y
CONFIG_STP=y
CONFIG_BRIDGE=y
CONFIG_BRIDGE_IGMP_SNOOPING=y
CONFIG_LLC=y
CONFIG_DST_CACHE=y
CONFIG_VXLAN=y
CONFIG_OVERLAY_FS=y
CONFIG_OVERLAY_FS_REDIRECT_ALWAYS_FOLLOW=y
```

I also had to create a veth pair in the Guest, to be able to configure a local IP, and patch k3s a bit to ensure the components will obey the `--advertise-address` and `--bind-address` flag and not try to guess the interface by looking at the default route.

And, even with all the changes in place, exposing a `NodePort` to the outside didn't work, because the method to do that is not compatible with AF_TSI-based networking. We could certainly find a way to make it work, but give the amount of changes (and, possibly, many more I haven't identified yet) required, I'd say this doesn't fit in krunvm/libkrun scope (lightweight VM and process isolation). I think QEMU, possibly with its `microvm` machine type, would do way better here.

On the other hand, one thing I'd like to explore is doing it the other way around, having k3s on the Host, but with a libkrun-enabled OCI runtime, so the containers are run with Virtualization-based isolation. I already tried this with [OpenFaaS](https://www.openfaas.com/), and I think it could be a good fit for k3s too.

**Comment by nickgerace** [comment]
Wow, this is an awesome investigation. Thanks for the deep dive, @slp. I appreciate the kernel feature breakdown as well.

> AF_TSI-based networking
I agree with the out-of-scope conclusion here. QEMU would more than likely be a better fit for this use case. Even with a "working" cluster and example, it seems to already be creeping out of the isolation scope.

I'd be willing to explore the latter use case, similarly to OpenFaaS. Is your investigation for this documented somewhere?

**Comment by nickgerace** [comment]
I believe this was fixed with https://github.com/containers/krunvm/pull/5, so I will close :)
